name: dart_course
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: iurimenin <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  archive : ^1.0.33
  pointycastle: ^0.11.1
  sqljocky5: "^1.0.0"

dev_dependencies:
  test: ^0.12.0
